"""Audit SDK warnings, JPEG exclusions, and reachable ingredient links.

No finding from this module proves that media was generated by AI. A valid
signature also cannot establish what happened before a capture device signed.
"""

from __future__ import annotations

from typing import Any
from pathlib import Path

from jpeg_audit import exclusion_coverage


ADDITIONAL_EXCLUSION_CODES = {
    "assertion.dataHash.additionalExclusionsPresent",
    "assertion.bmffHash.additionalExclusionsPresent",
    "assertion.boxesHash.additionalExclusionsPresent",
}
UNKNOWN_INGREDIENT_CODE = "ingredient.unknownProvenance"


def _audit_sdk(validation_results: Any) -> dict[str, Any]:
    """Separate structural concerns from cryptographic and content claims.

    A standard exclusion or an ordinary edit is not itself suspicious. SDK
    informational codes indicate *additional* exclusions or unavailable
    ingredient provenance; failures indicate invalid action/ingredient links.
    """
    active = validation_results.get("activeManifest") if isinstance(validation_results, dict) else None
    if not isinstance(active, dict):
        return {
            "status": "unknown",
            "checked": False,
            "coverage": "active_manifest_sdk_validation_codes",
            "message": "No active-manifest validation buckets were available for a pipeline audit.",
            "findings": [],
        }

    findings = []
    seen = set()
    for bucket in ("failure", "informational"):
        entries = active.get(bucket, [])
        if not isinstance(entries, list):
            return {
                "status": "unknown",
                "checked": False,
                "coverage": "active_manifest_sdk_validation_codes",
                "message": "The active-manifest validation buckets were malformed.",
                "findings": [],
            }
        for entry in entries:
            if not isinstance(entry, dict) or not isinstance(entry.get("code"), str):
                continue
            code = entry["code"]
            if code in seen:
                continue
            if code in ADDITIONAL_EXCLUSION_CODES:
                category, level, message = (
                    "additional_exclusion", "review",
                    "Additional bytes are outside the C2PA hard binding; inspect their purpose and content.",
                )
            elif code == UNKNOWN_INGREDIENT_CODE:
                category, level, message = (
                    "ingredient_provenance", "review",
                    "An ingredient has unknown provenance; this does not prove manipulation.",
                )
            elif bucket == "failure" and code.startswith(("assertion.action.", "assertion.ingredient.", "ingredient.")):
                category, level, message = (
                    "provenance_failure", "invalid",
                    "The C2PA validator reported a broken action or ingredient relationship.",
                )
            else:
                continue
            seen.add(code)
            findings.append({"code": code, "category": category, "level": level, "message": message})

    status = (
        "invalid" if any(item["level"] == "invalid" for item in findings)
        else "review_required" if findings else "no_flags"
    )
    messages = {
        "invalid": "The validator reported a structural provenance failure.",
        "review_required": "Additional exclusions or provenance gaps require review.",
        "no_flags": "No tracked pipeline warnings were reported by the C2PA validator.",
    }
    return {
        "status": status,
        "checked": True,
        "coverage": "active_manifest_sdk_validation_codes",
        "message": messages[status],
        "findings": findings,
    }


def _finding(code, level, message, category):
    return {"code": code, "level": level, "message": message, "category": category}


def _audit_graph(store):
    """Traverse only manifests reachable from the active SDK manifest.

    Missing local references are review findings: they may be external assets,
    not forged links. Hash authentication remains delegated to the C2PA SDK.
    """
    manifests = store.get("manifests")
    root = store.get("active_manifest")
    if not isinstance(manifests, dict) or not isinstance(root, str) or root not in manifests:
        return "unknown", [], 0
    findings, colors = [], {}
    stack = [(root, False)]
    edges = 0
    while stack:
        label, leaving = stack.pop()
        if leaving:
            colors[label] = 2
            continue
        if colors.get(label) == 1:
            findings.append(_finding("provo.history.cycle", "invalid", "A reachable ingredient chain contains a cycle.", "history"))
            continue
        if colors.get(label) == 2:
            continue
        if len(colors) >= 256:
            findings.append(_finding("provo.history.limit", "review", "The audit stopped at its manifest traversal limit.", "history"))
            return "limited", findings, len(colors)
        manifest = manifests.get(label)
        if not isinstance(manifest, dict):
            findings.append(_finding("provo.history.unavailable", "review", "A referenced ingredient manifest is not available locally.", "history"))
            continue
        colors[label] = 1
        stack.append((label, True))
        ingredients = manifest.get("ingredients", [])
        if not isinstance(ingredients, list):
            findings.append(_finding("provo.history.malformed", "review", "Ingredient metadata could not be interpreted.", "history"))
            continue
        for ingredient in ingredients:
            edges += 1
            if edges > 4096:
                findings.append(_finding("provo.history.limit", "review", "The audit stopped at its ingredient traversal limit.", "history"))
                return "limited", findings, len(colors)
            if not isinstance(ingredient, dict):
                findings.append(_finding("provo.history.malformed", "review", "An ingredient entry could not be interpreted.", "history"))
                continue
            if ingredient.get("relationship") == "inputTo":
                continue
            reference = ingredient.get("active_manifest")
            if not isinstance(reference, str) or not reference:
                findings.append(_finding("provo.history.unknownIngredient", "review", "An ingredient has no available signed manifest reference.", "history"))
            elif reference not in manifests:
                findings.append(_finding("provo.history.unavailable", "review", "A referenced ingredient manifest is not available locally.", "history"))
            else:
                stack.append((reference, False))
    return "checked", findings, len(colors)


def _audit_bytes(file_path, detailed_store):
    if not isinstance(detailed_store, dict):
        return "unavailable", [], {}
    manifests = detailed_store.get("manifests")
    root = detailed_store.get("active_manifest")
    if not isinstance(manifests, dict) or not isinstance(root, str):
        return "unavailable", [], {}
    active = manifests.get(root)
    assertions = active.get("assertion_store") if isinstance(active, dict) else None
    binding = assertions.get("c2pa.hash.data") if isinstance(assertions, dict) else None
    if not isinstance(binding, dict):
        # Update manifests, BMFF, box hashes, and collections need separate rules.
        return "unsupported_binding", [], {}
    if file_path is None:
        return "unavailable", [], {}
    path = Path(file_path)
    if path.stat().st_size > 25 * 1024 * 1024:
        return "limit_exceeded", [], {}
    size = path.stat().st_size
    exclusions = binding.get("exclusions", [])
    if not isinstance(exclusions, list):
        return "invalid", [_finding("provo.exclusion.malformed", "invalid", "The exclusion list is malformed.", "byte_coverage")], {}
    if len(exclusions) > 4096:
        return "limit_exceeded", [], {}
    ranges, previous_end = [], 0
    for exclusion in exclusions:
        start = exclusion.get("start") if isinstance(exclusion, dict) else None
        length = exclusion.get("length") if isinstance(exclusion, dict) else None
        if (type(start) is not int or type(length) is not int or start < 0 or length <= 0
                or start < previous_end or start + length > size):
            return "invalid", [_finding("provo.exclusion.invalidRange", "invalid", "An exclusion is overlapping, unordered, outside the file, or has invalid offsets.", "byte_coverage")], {}
        ranges.append((start, start + length))
        previous_end = start + length
    stats = {"file_bytes": size, "excluded_bytes": sum(end - start for start, end in ranges), "exclusion_count": len(ranges)}
    with path.open("rb") as source:
        data = source.read(25 * 1024 * 1024 + 1)
    if len(data) != size:
        return "unavailable", [], stats
    if not data.startswith(b"\xff\xd8"):
        return "unsupported_format", [], stats
    try:
        findings = exclusion_coverage(data, ranges)
    except ValueError as error:
        return "unavailable", [_finding("provo.jpeg.structureUnresolved", "review", str(error), "byte_coverage")], stats
    return "checked", findings, stats


def audit_pipeline(validation_results: Any, *, manifest_store=None, detailed_store=None, file_path=None):
    """Run all available checks; preserve limitations as explicit coverage.

    Optional inputs allow tests and integrations to use SDK signal checks alone.
    The upload integration supplies all inputs and withholds full trust whenever
    independent byte coverage cannot be established for the supported profile.
    """
    result = _audit_sdk(validation_results)
    coverage = {"sdk_signals": "checked" if result["checked"] else "unavailable"}
    findings = list(result["findings"])
    stats = {}
    if manifest_store is not None or file_path is not None:
        graph_status, graph_findings, count = _audit_graph(manifest_store or {})
        coverage["ingredient_graph"] = graph_status
        findings.extend(graph_findings)
        stats["manifests_visited"] = count
        try:
            byte_status, byte_findings, byte_stats = _audit_bytes(file_path, detailed_store)
        except OSError:
            byte_status, byte_findings, byte_stats = "unavailable", [], {}
        coverage["jpeg_exclusion_coverage"] = byte_status
        findings.extend(byte_findings)
        stats.update(byte_stats)
    incomplete = any(value != "checked" for value in coverage.values())
    status = ("invalid" if any(f["level"] == "invalid" for f in findings)
              else "review_required" if findings
              else "unknown" if incomplete else "no_flags")
    return {
        "version": "1.0", "status": status,
        "checked": any(value == "checked" for value in coverage.values()),
        "coverage": coverage, "statistics": stats, "findings": findings,
        "message": {
            "invalid": "Pipeline structure failed PROVO's policy checks.",
            "review_required": "Exclusions or provenance relationships require review.",
            "unknown": "Pipeline coverage is incomplete for this asset; full trust is withheld.",
            "no_flags": "No concerns were found within the reported audit coverage.",
        }[status],
        "limitations": [
            "APP11 envelope identity, signatures and hashes are validated by the C2PA SDK.",
            "Independent byte mapping currently supports JPEG with an active c2pa.hash.data assertion.",
            "This audit cannot identify AI-generated pixels or verify the camera sensor and pre-signing capture path.",
        ],
    }
